package com.aerometal.assignmentmanager.service;

import com.aerometal.assignmentmanager.entity.AccessRight;
import com.aerometal.assignmentmanager.exception.AccessRightNotFoundException;
import com.aerometal.assignmentmanager.repository.AccessRightRepository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AccessRightServiceTest {

    @Mock
    private AccessRightRepository repository;

    @InjectMocks
    private AccessRightService accessRightService;

    private AccessRight accessRight;

    @BeforeEach
    void setUp() {
        accessRight = new AccessRight();
        accessRight.setId(1L);
        accessRight.setName("READ");

        // Add other fields if your AccessRight entity has them.
        // accessRight.setDescription("Read access");
    }

    // =========================================================
    // findAll()
    // =========================================================

    @Test
    void findAll_whenAccessRightsExist_shouldReturnAllAccessRights() {

        AccessRight writeRight = new AccessRight();
        writeRight.setId(2L);
        writeRight.setName("WRITE");

        when(repository.findAll())
                .thenReturn(List.of(accessRight, writeRight));

        List<AccessRight> result =
                accessRightService.findAll();

        assertNotNull(result);
        assertEquals(2, result.size());

        assertEquals(accessRight, result.get(0));
        assertEquals(writeRight, result.get(1));

        verify(repository).findAll();
    }

    @Test
    void findAll_whenNoAccessRightsExist_shouldReturnEmptyList() {

        when(repository.findAll())
                .thenReturn(List.of());

        List<AccessRight> result =
                accessRightService.findAll();

        assertNotNull(result);
        assertTrue(result.isEmpty());

        verify(repository).findAll();
    }

    // =========================================================
    // findById()
    // =========================================================

    @Test
    void findById_whenAccessRightExists_shouldReturnAccessRight() {

        Long id = 1L;

        when(repository.findById(id))
                .thenReturn(Optional.of(accessRight));

        AccessRight result =
                accessRightService.findById(id);

        assertNotNull(result);

        assertEquals(1L, result.getId());
        assertEquals("READ", result.getName());

        verify(repository).findById(id);
    }

    @Test
    void findById_whenAccessRightDoesNotExist_shouldThrowException() {

        Long id = 99L;

        when(repository.findById(id))
                .thenReturn(Optional.empty());

        AccessRightNotFoundException exception =
                assertThrows(
                		AccessRightNotFoundException.class,
                        () -> accessRightService.findById(id)
                );

        assertEquals(
                "Access right not found: 99",
                exception.getMessage()
        );

        verify(repository).findById(id);
    }

    // =========================================================
    // create()
    // =========================================================

    @Test
    void create_shouldClearIdAndSaveAccessRight() {

        AccessRight newAccessRight = new AccessRight();

        // Deliberately provide an ID.
        // The service should ignore it.
        newAccessRight.setId(999L);
        newAccessRight.setName("WRITE");

        when(repository.save(newAccessRight))
                .thenAnswer(invocation -> {

                    AccessRight saved =
                            invocation.getArgument(0);

                    // Simulate an ID generated by the database.
                    saved.setId(2L);

                    return saved;
                });

        AccessRight result =
                accessRightService.create(newAccessRight);

        assertNotNull(result);

        assertEquals(2L, result.getId());
        assertEquals("WRITE", result.getName());

        verify(repository).save(newAccessRight);
    }

    @Test
    void create_shouldSetIdToNullBeforeRepositorySave() {

        AccessRight newAccessRight = new AccessRight();
        newAccessRight.setId(999L);
        newAccessRight.setName("WRITE");

        when(repository.save(any(AccessRight.class)))
                .thenAnswer(invocation ->
                        invocation.getArgument(0));

        accessRightService.create(newAccessRight);

        assertNull(newAccessRight.getId());

        verify(repository).save(newAccessRight);
    }

    // =========================================================
    // update()
    // =========================================================

    @Test
    void update_whenAccessRightExists_shouldUpdateAccessRight() {

        Long id = 1L;

        AccessRight updatedAccessRight =
                new AccessRight();

        updatedAccessRight.setName("ADMIN");

        when(repository.existsById(id))
                .thenReturn(true);

        when(repository.save(updatedAccessRight))
                .thenReturn(updatedAccessRight);

        AccessRight result =
                accessRightService.update(
                        id,
                        updatedAccessRight
                );

        assertNotNull(result);

        assertEquals(id, result.getId());
        assertEquals("ADMIN", result.getName());

        verify(repository).existsById(id);
        verify(repository).save(updatedAccessRight);
    }

    @Test
    void update_shouldReplaceIncomingIdWithRequestedId() {

        Long requestedId = 1L;

        AccessRight updatedAccessRight =
                new AccessRight();

        // Deliberately give it the wrong ID.
        updatedAccessRight.setId(999L);
        updatedAccessRight.setName("ADMIN");

        when(repository.existsById(requestedId))
                .thenReturn(true);

        when(repository.save(updatedAccessRight))
                .thenReturn(updatedAccessRight);

        AccessRight result =
                accessRightService.update(
                        requestedId,
                        updatedAccessRight
                );

        assertEquals(
                requestedId,
                result.getId()
        );

        assertEquals(
                requestedId,
                updatedAccessRight.getId()
        );

        verify(repository)
                .existsById(requestedId);

        verify(repository)
                .save(updatedAccessRight);
    }

    @Test
    void update_whenAccessRightDoesNotExist_shouldThrowException() {

        Long id = 99L;

        AccessRight updatedAccessRight =
                new AccessRight();

        updatedAccessRight.setName("ADMIN");

        when(repository.existsById(id))
                .thenReturn(false);

        AccessRightNotFoundException exception =
                assertThrows(
                		AccessRightNotFoundException.class,
                        () -> accessRightService.update(
                                id,
                                updatedAccessRight
                        )
                );

        assertEquals(
                "Access right not found: 99",
                exception.getMessage()
        );

        verify(repository).existsById(id);

        // An invalid update must never be saved.
        verify(repository, never())
                .save(any(AccessRight.class));
    }

    // =========================================================
    // delete()
    // =========================================================

    @Test
    void delete_whenAccessRightExists_shouldDeleteAccessRight() {

        Long id = 1L;

        when(repository.existsById(id))
                .thenReturn(true);

        accessRightService.delete(id);

        verify(repository).existsById(id);
        verify(repository).deleteById(id);
    }

    @Test
    void delete_whenAccessRightDoesNotExist_shouldThrowException() {

        Long id = 99L;

        when(repository.existsById(id))
                .thenReturn(false);

        AccessRightNotFoundException exception =
                assertThrows(
                		AccessRightNotFoundException.class,
                        () -> accessRightService.delete(id)
                );

        assertEquals(
                "Access right not found: 99",
                exception.getMessage()
        );

        verify(repository).existsById(id);

        // Important: don't try to delete a nonexistent record.
        verify(repository, never())
                .deleteById(anyLong());
    }
}